apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  selector:
    app: mariadb
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP  # MariaDB는 보통 외부에서 접근할 필요 없으므로 ClusterIP로 설정
