apiVersion: v1
kind: Service
metadata:
  name: my-spring-app
spec:
  selector:
    app: my-spring-app
  ports:
    - protocol: TCP
      port: 8080  # 외부에서 접근할 포트
      targetPort: 8080  # 컨테이너 내부의 포트
  type: NodePort  # 외부에서 접근하려면 NodePort를 사용하거나 LoadBalancer를 사용할 수 있음
